export const MAKE_ANNOUNCEMENT_START = "MAKE_ANNOUNCEMENT_START";
export const MAKE_ANNOUNCEMENT_SUCCESS = "MAKE_ANNOUNCEMENT_SUCCESS";
export const MAKE_ANNOUNCEMENT_FAIL = "MAKE_ANNOUNCEMENT_FAIL";
export const FETCH_CLASS_ANNOUNCEMENT_START = "FETCH_CLASS_ANNOUNCEMENT_START";
export const FETCH_CLASS_ANNOUNCEMENT_SUCCESS = "FETCH_CLASS_ANNOUNCEMENT_SUCCESS";
export const FETCH_CLASS_ANNOUNCEMENT_FAIL = "FETCH_CLASS_ANNOUNCEMENT_FAIL";