export const FETCH_COURSE_START = "FETCH_COURSE_START";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_FAIL = "FETCH_COURSE_FAIL";
export const FETCH_SCHOOL_TERM_START = "FETCH_SCHOOL_TERM_START";
export const FETCH_SCHOOL_TERM_SUCCESS = "FETCH_SCHOOL_TERM_SUCCESS";
export const FETCH_SCHOOL_TERM_FAIL = "FETCH_SCHOOL_TERM_FAIL";