export const FECTH_USER_PROFILE_START = "FECTH_USER_PROFILE_START";
export const FECTH_USER_PROFILE_SUCCESS = "FECTH_USER_PROFILE_SUCCESS";
export const FECTH_USER_PROFILE_FAIL = "FECTH_USER_PROFILE_FAIL";
export const FECTH_UNFINISHED_VIDEO_START = "FECTH_UNFINISHED_VIDEO_START";
export const FECTH_UNFINISHED_VIDEO_SUCCESS = "FECTH_UNFINISHED_VIDEO_SUCCESS";
export const FECTH_UNFINISHED_VIDEO_FAIL = "FECTH_UNFINISHED_VIDEO_FAIL";