export const FETCH_EXAMS_START = "FETCH_EXAMS_START";
export const FETCH_EXAMS_SUCCESS = "FETCH_EXAMS_SUCCESS";
export const FETCH_EXAMS_FAIL = "FETCH_EXAMS_FAIL";
export const ADD_EXAMS_START = "ADD_EXAMS_START";
export const ADD_EXAMS_SUCCESS = "ADD_EXAMS_SUCCESS";
export const ADD_EXAMS_FAIL = "ADD_EXAMS_FAIL";