export const SIGN_UP_FOR_A_CHILD_START = "SIGN_UP_FOR_A_CHILD_START";
export const SIGN_UP_FOR_A_CHILD_SUCCESS = "SIGN_UP_FOR_A_CHILD_SUCCESS";
export const SIGN_UP_FOR_A_CHILD_FAIL = "SIGN_UP_FOR_A_CHILD_FAIL";
export const FETCH_CHILDREN_START = "FETCH_CHILDREN_START";
export const FETCH_CHILDREN_SUCCESS = "FETCH_CHILDREN_SUCCESS";
export const FETCH_CHILDREN_FAIL = "FETCH_CHILDREN_FAIL";