export const FETCH_PAYMENT_PLANS_START = "FETCH_PAYMENT_PLANS_START";
export const FETCH_PAYMENT_PLANS_SUCCESS = "FETCH_PAYMENT_PLANS_SUCCESS";
export const FETCH_PAYMENT_PLANS_FAIL = "FETCH_PAYMENT_PLANS_FAIL";