export const FECTH_USER_PROFILE_START = "FECTH_USER_PROFILE_START";
export const FECTH_USER_PROFILE_SUCCESS = "FECTH_USER_PROFILE_SUCCESS";
export const FECTH_USER_PROFILE_FAIL = "FECTH_USER_PROFILE_FAIL";