export const FETCH_CLASS_SUBJECTS_START = "FETCH_CLASS_SUBJECTS_START";
export const FETCH_CLASS_SUBJECTS_SUCCESS = "FETCH_CLASS_SUBJECTS_SUCCESS";
export const FETCH_CLASS_SUBJECTS_FAIL = "FETCH_CLASS_SUBJECTS_FAIL";