export const FETCH_CLASS_SUBJECTS_START = "FETCH_CLASS_SUBJECTS_START";
export const FETCH_CLASS_SUBJECTS_SUCCESS = "FETCH_CLASS_SUBJECTS_SUCCESS";
export const FETCH_CLASS_SUBJECTS_FAIL = "FETCH_CLASS_SUBJECTS_FAIL";
export const FETCH_ACTIVITIES_START = "FETCH_ACTIVITIES_START";
export const FETCH_ACTIVITIES_SUCCESS = "FETCH_ACTIVITIES_SUCCESS";
export const FETCH_ACTIVITIES_FAIL = "FETCH_ACTIVITIES_FAIL";