export const boardData = [
    {
        name: "Sunday Olorunsheyi",
        role: "Co-founder, Pertinence Group",
        image: '/assets/img/Sunday.jpg',
        summary: "Sunday Olorunsheyi is a successful serial entrepreneur, a business and management consultant, an investment advisor, and a global keynote speaker. He also serves a vast number of clientele in different fields on matters of Management Strategy Development, Business Expansion, Product/Service Development, Activation & Adaptation, Sales and Marketing, Portfolio Management, Investment Risk Assessment, and General Business Development. Olorunsheyi has been able to undeniably take a rightful seat as a globally recognized and successful businessman. He is the Co-Founder of Pertinence Group, a multi-billion Enterprise Development and People Empowerment Company, having a workforce of over 5000 associates, with major interests in Technology, Real Estate, Agriculture, Media and Financial Services.Olorunsheyi as an advocate of growth, innovation, and development is also well known for his activities with regards to proper management of talent, skills and resources and creating enabling environment for young Nigerians in the Real estate sector and in other endeavours. As a man who loves to give back to people, he is known to help business owners and young folks alike to make headways through training and guidance using the Olorunsheyi Mentorship Program as a platform. In addition to this, his love to further make an impact is expressed through many philanthropic acts carried out by his foundation “The Olorunsheyi Foundation” which constantly addresses and tackles issues of poverty alleviation, poor education, and community health.        He is a knowledge lover and has bagged two master’s degrees in business administration and Public Administration from reputable institutions including the Business School Netherlands. He is currently studying for a Ph.D. at Charisma University."
    },
    {
        name: "Olusola Adeola",
        role: "ED, Designing Futures",
        image: '/assets/img/Adeola.jpg',
        summary: "Sola is a strategic thinker and a collector of a wide variety of skills and information with the singular focus of improving the lives of the people around her. She is a builder, working to create organizational structures and systems, and effectively deploy resources. Sola has a strong passion for education development and envisions a future in which every African child gains access to quality education that would enable them to dream, create their future, live out their best lives and reshape the future of the continent. Sola has over 14 years’ work experience as a strategy and organization development consultant working across the private sector, the public sector and the development sector. She has both local and global work experience in institutions such as Accenture, the Clinton Foundation, Dalberg and ESSPIN (a UKaid Initiative in Nigeria). In the non-profit sector, Sola has pioneered in a number of fields, from a start-up political party (Kowa Party) to Nigeria’s first innovation hub as the Coordinator of the FATE Institute for Venture Design (IVD), an initiative between Stanford’s Centre for Design Research (CDR) and FATE Foundation. Sola recently worked as the Executive Secretary of Freedom Foundation and subsequently, the Head of Corporate Strategy for LAT Cleveson Group (www.latcleveson.com), a diversified conglomerate with subsidiaries in maritime, agriculture and retail.   Given her passion for education, Sola co-founded Designing Futures, an education platform to promote innovative solutions that would empower generations to ‘design their future’. In collaboration with Incubator Africa, she led the establishment of Imaginal Education Initiative, a network organization of Imaginal Education (www.imaginaleducation.com). She often collaborates on reform initiatives in the education sector and works as a freelance consultant. Sola has co-authored Civics Textbooks published by Kachifo Ltd, used in private primary and secondary schools in Nigeria. Sola has a Bachelor of Science in Foreign Service (BSFS) from Georgetown University and a Masters in Public Administration (MPA) from Columbia University’s School of International and Public Affairs (SIPA), focused on Education Policy. She is also a Kauffman fellow (www.kauffmanfellows.org)."
    },
    {
        name: "Chude Jideonwo",
        role: "Founder, Joy Inc.",
        image: '/assets/img/Chude.jpg',
        summary: "Chude Jideonwo is Co-Founder of the media group RED, and human flourishing company Joy, Inc. Chude's work centers on storytelling from across disciplines, to inspire new, human-centered narratives about politics, markets, faith, identity, and society in Africa. He is also host of #WithChude – a network of media products across TV, radio, podcast, newsletter, and blog - telling stories that enable and strengthen the mind, the heart, and the spirit. RED, one of Africa’s leading media content and consulting companies, has worked on national elections and social movements in Nigeria, Ghana, Kenya, Sierra Leone and Senegal, and Joy, Inc. has worked with organizations from the Ford Motor Company to the Lagos State Government on building safe, warm spaces across business, government and culture. All of Joy, Inc.’s profits are invested in The Joy Hubs – co-working spaces and walk-in centers for young people dealing with mental health challenges, with a focus on depression and anxiety."
    },
    {
        name: "Titi Akinsanmi",
        role: "Policy Lead, Google",
        image: '/assets/img/Akinsanmi.jpeg',
        summary: "Titi Akinsanmi is a Digital Policy expert who currently serves as Policy and Government Relations Lead for West and Francophone Africa at Google. With 20+ years of experience, Titi has directly engaged with global policy development processes, built capacity and strategy, and is enabling the implementation of strategies as it relates to Internet governance and the digital economy. A published academic, Titi holds a certificate in English common Law from University of London, BA in English from OAU, Ile-Ife; a Masters in Public Policy from the University of Witwatersrand in South Africa; and an LLM from Osgoode Law School (specializing in Privacy and Cybersecurity). She was a Fellow at the Berkman Klein Centre for Internet and Society at Harvard from 2018 – 2020, sits on the boards of digital economy, arts and youth development-related institutions, and serves on the World Economic Forum’s Global Future Council on the Digital economy."
    },
    {
        name: "Mary Akpobome",
        role: "COO, Imperium Capital Partners Plc",
        image: '/assets/img/Mary-Akpobome.jpg',
        summary: "Mary Akpobome is the Chief Operating Officer of Imperium Capital Partners Plc (Formerly HBCL Investment Services Plc) a private Investments company. Prior to her appointment to Imperial Capital Plc, Mary was the Executive Director, Business Banking overseeing all Corporate, Commercial, Special Projects, Intervention Schemes, Multilaterals, Agriculture and Export Businesses of Heritage Bank. A Fellow of the Institute of Credit Administrators, Mary holds an MBA from the University of Lagos and a Bachelor’s degree in Theatre Arts from the University of Benin, Edo State, Nigeria. She is an Alumnus of Lagos Business School, London Business School and INSEAD (France); Mary has attended courses at Stanford Graduate School, Harvard Business School, Kellogg Executive Education and well as IMD (Switzerland). In 2015, following the acquisition of Enterprise Bank Limited by Heritage Bank Plc, Mary was appointed the Acting Managing Director of Enterprise Bank Limited. Her solid experience in the management of people and resources was instrumental in stabilizing the operations of the bank, improving its service orientation and preparing it for a seamless integration with Heritage Bank Plc. A consummate Banker with over 30 years cognate experience and vast proficiency and skills in Credit Management, Commercial and Retail strategies, Mary began her banking career with Citizens International Bank serving in different departments before joining Platinum Bank Ltd in 2001 and rose to the position of Executive Director Designate in 2008 overseeing the Service Bank of Bank PHB. In 2009, Mary was part of the Executive Team of the core investor that acquired the former SocietieGenerale Bank. An astute manager of people and resources, Mary is a team leader with extensive experience in the private and public sectors. A member of the Institute of Directors, Chartered Institute of Bankers in Scotland and Nigeria, Mary is also the co-Founder (Founded with her husband Mr. Atunyota Ali Baba Akpobome) of The Purple Girl Foundation – a Foundation focused on providing opportunities in education for young underprivileged girls."
    },
    {
        name: "Ngozi Ayanru",
        role: "Managing Partner, Realty Invest",
        image: '/assets/img/Ngozi-Ayanru.jpg',
        summary: "Mrs. Ngozi Ayanru studied Management & Accounting at the Obafemi Awolowo University. She’s a fellow of the Association of Chartered Certified Accountants, UK. She has over 20years valuable work experience including the Management Development Program in First City Monument Bank which equipped her through hands-on experience in Corporate, Consumer & Retail Banking, Treasury, International Trade and Domestic Operations. She was the assistant manager at a branch of the before moving to the Oil & Gas sector in 2002. In ExxonMobil, she held several supervisory roles in various functions including Taxation, Financial Reporting, Joint Venture Management, General Ledger and Balance Sheet Management which equipped her with rich cross-functional skills and commercial experience in the industry. She left ExxonMobil to commence her business in 2014 and is currently the Managing Partner of Realty Invest & Trust Partners (RITP) a company that focuses on real estate investments including construction, sales & acquisitions, facility management and agency. She loves houses, traveling to new places and experiencing new things, dancing, and supporting the underserved in various ways. She has been a part of the Bethesda family for almost 10 years."
    },
]